// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blvqoxwphootxstvffsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsdnFveHdwaG9vdHhzdHZmZnNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjU3MjcsImV4cCI6MjA2NTUwMTcyN30.GNWPt_6VOP6JdkICayom0D5ZOwfIE5BQcVVly7CDUbQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);